apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: amr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: container
          image: docker.io/amrabunemr98/test:build-${BUILD_NUMBER}-app
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: svc-app
  namespace: amr
spec:
  selector:
    app: test-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
